name: XXL Job CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions: write-all

jobs:
  build_all:
    name: Compile with JDK 8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: adopt
          java-version: 8

      - name: Build Maven Application
        shell: bash
        run: mvn -B package --file pom.xml

      - name: Create SBOM For xxl-job-admin
        uses: anchore/sbom-action@v0.15.10
        with:
          path: ./xxl-job-admin/target/
          artifact-name: xxl-job-admin-sbom.cyclonedx
          dependency-snapshot: true
          format: cyclonedx-json

      - name: Create SBOM For xxl-job-core
        uses: anchore/sbom-action@v0.15.10
        with:
          path: ./xxl-job-core/target/
          artifact-name: xxl-job-core-sbom.cyclonedx
          dependency-snapshot: true
          format: cyclonedx-json

      - name: Create SBOM For xxl-job-executor-sample-frameless
        uses: anchore/sbom-action@v0.15.10
        with:
          path: ./xxl-job-executor-samples/xxl-job-executor-sample-frameless/target/
          artifact-name: xxl-job-executor-sample-frameless-sbom.cyclonedx
          dependency-snapshot: true
          format: cyclonedx-json

      - name: Create SBOM For xxl-job-executor-sample-springboot
        uses: anchore/sbom-action@v0.15.10
        with:
          path: ./xxl-job-executor-samples/xxl-job-executor-sample-springboot/target/
          artifact-name: xxl-job-executor-sample-springboot-sbom.cyclonedx
          dependency-snapshot: true
          format: cyclonedx-json

      - name: Tar Maven Build Repository
        shell: bash
        run: tar -czf maven-build.tgz -C ~ .m2/repository

      - name: Upload Maven Build Repository
        uses: actions/upload-artifact@v4
        with:
          name: maven-build
          path: maven-build.tgz

      - name: Generate Maven Dependency Tree
        shell: bash
        run: mvn compile dependency:tree -DoutputFile=maven_dep_tree.txt

      - name: Create Maven Dependency Tree Zip File
        shell: bash
        run: find . -type f -name 'maven_dep_tree.txt' -exec zip -r mvn-dependency-tree.zip {} +

      - name: Upload Maven Dependency Tree Zip
        uses: actions/upload-artifact@v4
        with:
          name: maven-dependency-tree
          path: mvn-dependency-tree.zip

  eclipse_steady_scan:
    needs: [ build_all ]
    name: Run SCA Eclipse Steady Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Maven Build
        uses: actions/download-artifact@v4
        with:
          name: maven-build
          path: .

      - name: Extract Maven Build
        shell: bash
        run: tar -xzf maven-build.tgz -C ~

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: adopt
          java-version: 8

      - name: Run Eclipse Steady Scan
        shell: bash
        run: mvn compile -Dsteady compile steady:app steady:report

      - name: Upload Eclipse Steady Scan Json Results
        uses: actions/upload-artifact@v4
        with:
          name: eclipse-steady-scan-reports-json
          path: '**/vulas-report.json'

      - name: Upload Eclipse Steady Scan Html Results
        uses: actions/upload-artifact@v4
        with:
          name: eclipse-steady-scan-reports-html
          path: '**/vulas-report.html'

  owasp_dependency_check:
    needs: [build_all]
    name: Run SCA OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Maven Build
        uses: actions/download-artifact@v4
        with:
          name: maven-build
          path: .

      - name: Extract Maven Build
        shell: bash
        run: tar -xzf maven-build.tgz -C ~

      - name: Run OWASP Dependency Check (JSON)
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: xxl-job
          path: .
          format: JSON
          args: >
            --enableRetired

      - name: Upload OWASP Dependency Check Results
        uses: actions/upload-artifact@v4
        with:
          name: OWASP Dependency Check Report (JSON)
          path: ${{github.workspace}}/reports

      - name: Run OWASP Dependency Check (HTML)
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: xxl-job
          path: .
          format: HTML
          args: >
            --enableRetired

      - name: Upload OWASP Dependency Check Results
        uses: actions/upload-artifact@v4
        with:
          name: OWASP Dependency Check Report (HTML)
          path: ${{github.workspace}}/reports