name: XXL Job CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build_application:
    name: Compile with JDK 8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: adopt
          java-version: 8

      - name: Build Maven Application
        shell: bash
        run: mvn -B package --file pom.xml

      - name: Create SBOM For xxl-job-admin
        uses: anchore/sbom-action@v0.15.10
        with:
          path: ./xxl-job-admin/target/
          artifact-name: xxl-job-admin-sbom.cyclonedx
          dependency-snapshot: true
          format: cyclonedx-json

      - name: Create SBOM For xxl-job-core
        uses: anchore/sbom-action@v0.15.10
        with:
          path: ./xxl-job-core/target/
          artifact-name: xxl-job-core-sbom.cyclonedx
          dependency-snapshot: true
          format: cyclonedx-json

      - name: Create SBOM For xxl-job-executor-sample-frameless
        uses: anchore/sbom-action@v0.15.10
        with:
          path: ./xxl-job-executor-samples/xxl-job-executor-sample-frameless/target/
          artifact-name: xxl-job-executor-sample-frameless-sbom.cyclonedx
          dependency-snapshot: true
          format: cyclonedx-json

      - name: Create SBOM For xxl-job-executor-sample-springboot
        uses: anchore/sbom-action@v0.15.10
        with:
          path: ./xxl-job-executor-samples/xxl-job-executor-sample-springboot/target/
          artifact-name: xxl-job-executor-sample-springboot-sbom.cyclonedx
          dependency-snapshot: true
          format: cyclonedx-json

      - name: Tar Maven Build Repository
        shell: bash
        run: tar -czf maven-build.tgz -C ~ .m2/repository

      - name: Upload Maven Build Repository
        uses: actions/upload-artifact@v4
        with:
          name: maven-build
          path: maven-build.tgz

      - name: Generate Maven Dependency Tree
        shell: bash
        run: mvn compile dependency:tree -DoutputFile=maven_dep_tree.txt

      - name: Create Maven Dependency Tree Zip File
        shell: bash
        run: find . -type f -name 'maven_dep_tree.txt' -exec zip -r mvn-dependency-tree.zip {} +

      - name: Upload Maven Dependency Tree Zip
        uses: actions/upload-artifact@v4
        with:
          name: maven-dependency-tree
          path: mvn-dependency-tree.zip

  run_sca_scanning:
    needs: [ build_application ]
    name: Run SCA Scanning Workflow
    uses: seansmith39/H6060-Experiment-1-SCA-Scans/.github/workflows/sca_scan_mvn.yml@v1.0.0
    secrets: inherit
    with:
      project-name: xxl-job
      java-version: 8
      java-distribution: adopt
      mvn-build-artifact: maven-build

  run_sast_scanning:
    needs: [ build_application ]
    name: Run SAST Scanning Workflow
    uses: seansmith39/H6060-Experiment-1-SAST-Scans/.github/workflows/sast_scan_mvn.yml@v1.0.2
    secrets: inherit
    with:
      sonarqube-project-name: xxl-job-H6060
      mvn-build-command: mvn -B package --file pom.xml
      deepsource-scan-enabled: false

